# Generated by Django 3.2.8 on 2021-11-10 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='a_last_updated',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='d_last_updated',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='h_last_updated',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='m_last_updated',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='w_last_updated',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='y_last_updated',
            field=models.IntegerField(default=0),
        ),
    ]
