# Generated by Django 3.2.8 on 2021-11-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineup',
            name='name',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
