# Generated by Django 3.2.8 on 2021-11-12 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineup',
            name='price',
            field=models.DecimalField(decimal_places=10, max_digits=25, null=True),
        ),
    ]
