# Generated by Django 3.2.8 on 2021-11-14 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_lineup_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='starting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lineup',
            name='cgID',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
