# Generated by Django 3.2.8 on 2021-11-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20211113_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineup',
            name='cgID',
        ),
        migrations.RemoveField(
            model_name='lineup',
            name='name',
        ),
        migrations.RemoveField(
            model_name='lineup',
            name='symbol',
        ),
        migrations.AddField(
            model_name='lineup',
            name='map_id',
            field=models.IntegerField(default=0),
        ),
    ]
