# Generated by Django 3.2.8 on 2021-11-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20211118_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ending',
            field=models.BooleanField(default=False),
        ),
    ]
