# Generated by Django 3.2.8 on 2021-11-19 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_game_ending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='ending',
        ),
    ]
