# Generated by Django 3.2.8 on 2021-11-19 19:48

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0009_remove_game_ending'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=10, max_digits=25, null=True)),
                ('bet', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tier', models.CharField(max_length=8, null=True)),
                ('lineup', models.JSONField(default=dict)),
                ('portfolio', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(default=dict), size=None)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
