# Generated by Django 3.2.8 on 2021-11-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_playerhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerhistory',
            name='won',
            field=models.DecimalField(decimal_places=10, max_digits=10, null=True),
        ),
    ]
