# Generated by Django 3.2.8 on 2021-11-19 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_alter_playerhistory_won'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerhistory',
            name='won',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True),
        ),
    ]
