# Generated by Django 3.2.8 on 2021-11-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_alter_playerhistory_won'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerhistory',
            name='ranking',
            field=models.IntegerField(default=0),
        ),
    ]
