# Generated by Django 3.2.8 on 2021-11-28 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_alter_game_split'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='pot',
            field=models.IntegerField(default=0),
        ),
    ]
