# Generated by Django 3.2.8 on 2021-11-19 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_frozen_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_games', models.IntegerField(default=0)),
                ('games_won', models.IntegerField(default=0)),
                ('games_lost', models.IntegerField(default=0)),
                ('total_bets', models.DecimalField(decimal_places=8, max_digits=17, null=True)),
                ('amount_won', models.DecimalField(decimal_places=8, max_digits=17, null=True)),
                ('amount_lost', models.DecimalField(decimal_places=8, max_digits=17, null=True)),
                ('favorites', models.JSONField(default=dict)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
            options={
                'db_table': 'Stats',
            },
        ),
    ]
