# Generated by Django 3.2.8 on 2021-11-21 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_stats_tiers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stats',
            old_name='amount_lost',
            new_name='mult_amount_lost',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='amount_won',
            new_name='mult_amount_won',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='games_lost',
            new_name='mult_games_lost',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='games_won',
            new_name='mult_games_won',
        ),
        migrations.AddField(
            model_name='stats',
            name='tiered_amount_lost',
            field=models.DecimalField(decimal_places=8, max_digits=17, null=True),
        ),
        migrations.AddField(
            model_name='stats',
            name='tiered_amount_won',
            field=models.DecimalField(decimal_places=8, max_digits=17, null=True),
        ),
        migrations.AddField(
            model_name='stats',
            name='tiered_games_lost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='tiered_games_won',
            field=models.IntegerField(default=0),
        ),
    ]
