# Generated by Django 3.2.8 on 2021-11-21 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20211121_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stats',
            old_name='total_bets',
            new_name='mult_total_bets',
        ),
        migrations.AddField(
            model_name='stats',
            name='tiered_total_bets',
            field=models.DecimalField(decimal_places=8, max_digits=17, null=True),
        ),
    ]
