# Generated by Django 3.2.8 on 2021-11-05 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='key',
            field=models.CharField(max_length=43, primary_key=True, serialize=False),
        ),
    ]
